// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.activiti.spring.rest.model.FormProperty;
import org.activiti.spring.rest.model.FormPropertyDataOnDemand;
import org.activiti.spring.rest.model.FormPropertyIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FormPropertyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FormPropertyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FormPropertyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FormPropertyIntegrationTest: @Transactional;
    
    @Autowired
    FormPropertyDataOnDemand FormPropertyIntegrationTest.dod;
    
    @Test
    public void FormPropertyIntegrationTest.testCountFormPropertys() {
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to initialize correctly", dod.getRandomFormProperty());
        long count = FormProperty.countFormPropertys();
        Assert.assertTrue("Counter for 'FormProperty' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FormPropertyIntegrationTest.testFindFormProperty() {
        FormProperty obj = dod.getRandomFormProperty();
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to provide an identifier", id);
        obj = FormProperty.findFormProperty(id);
        Assert.assertNotNull("Find method for 'FormProperty' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FormProperty' returned the incorrect identifier", id, obj.getId_());
    }
    
    @Test
    public void FormPropertyIntegrationTest.testFindAllFormPropertys() {
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to initialize correctly", dod.getRandomFormProperty());
        long count = FormProperty.countFormPropertys();
        Assert.assertTrue("Too expensive to perform a find all test for 'FormProperty', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FormProperty> result = FormProperty.findAllFormPropertys();
        Assert.assertNotNull("Find all method for 'FormProperty' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FormProperty' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FormPropertyIntegrationTest.testFindFormPropertyEntries() {
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to initialize correctly", dod.getRandomFormProperty());
        long count = FormProperty.countFormPropertys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FormProperty> result = FormProperty.findFormPropertyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FormProperty' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FormProperty' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FormPropertyIntegrationTest.testFlush() {
        FormProperty obj = dod.getRandomFormProperty();
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to provide an identifier", id);
        obj = FormProperty.findFormProperty(id);
        Assert.assertNotNull("Find method for 'FormProperty' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFormProperty(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FormProperty' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FormPropertyIntegrationTest.testMergeUpdate() {
        FormProperty obj = dod.getRandomFormProperty();
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to provide an identifier", id);
        obj = FormProperty.findFormProperty(id);
        boolean modified =  dod.modifyFormProperty(obj);
        Integer currentVersion = obj.getVersion();
        FormProperty merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId_(), id);
        Assert.assertTrue("Version for 'FormProperty' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FormPropertyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to initialize correctly", dod.getRandomFormProperty());
        FormProperty obj = dod.getNewTransientFormProperty(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FormProperty' identifier to be null", obj.getId_());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'FormProperty' identifier to no longer be null", obj.getId_());
    }
    
    @Test
    public void FormPropertyIntegrationTest.testRemove() {
        FormProperty obj = dod.getRandomFormProperty();
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'FormProperty' failed to provide an identifier", id);
        obj = FormProperty.findFormProperty(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FormProperty' with identifier '" + id + "'", FormProperty.findFormProperty(id));
    }
    
}
