// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.activiti.spring.rest.model.ProcessInstance;
import org.activiti.spring.rest.model.ProcessInstanceDataOnDemand;
import org.activiti.spring.rest.model.ProcessInstanceIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProcessInstanceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProcessInstanceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProcessInstanceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProcessInstanceIntegrationTest: @Transactional;
    
    @Autowired
    ProcessInstanceDataOnDemand ProcessInstanceIntegrationTest.dod;
    
    @Test
    public void ProcessInstanceIntegrationTest.testCountProcessInstances() {
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to initialize correctly", dod.getRandomProcessInstance());
        long count = ProcessInstance.countProcessInstances();
        Assert.assertTrue("Counter for 'ProcessInstance' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProcessInstanceIntegrationTest.testFindProcessInstance() {
        ProcessInstance obj = dod.getRandomProcessInstance();
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to provide an identifier", id);
        obj = ProcessInstance.findProcessInstance(id);
        Assert.assertNotNull("Find method for 'ProcessInstance' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProcessInstance' returned the incorrect identifier", id, obj.getId_());
    }
    
    @Test
    public void ProcessInstanceIntegrationTest.testFindAllProcessInstances() {
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to initialize correctly", dod.getRandomProcessInstance());
        long count = ProcessInstance.countProcessInstances();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProcessInstance', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProcessInstance> result = ProcessInstance.findAllProcessInstances();
        Assert.assertNotNull("Find all method for 'ProcessInstance' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProcessInstance' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProcessInstanceIntegrationTest.testFindProcessInstanceEntries() {
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to initialize correctly", dod.getRandomProcessInstance());
        long count = ProcessInstance.countProcessInstances();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProcessInstance> result = ProcessInstance.findProcessInstanceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProcessInstance' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProcessInstance' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProcessInstanceIntegrationTest.testFlush() {
        ProcessInstance obj = dod.getRandomProcessInstance();
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to provide an identifier", id);
        obj = ProcessInstance.findProcessInstance(id);
        Assert.assertNotNull("Find method for 'ProcessInstance' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProcessInstance(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProcessInstance' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProcessInstanceIntegrationTest.testMergeUpdate() {
        ProcessInstance obj = dod.getRandomProcessInstance();
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to provide an identifier", id);
        obj = ProcessInstance.findProcessInstance(id);
        boolean modified =  dod.modifyProcessInstance(obj);
        Integer currentVersion = obj.getVersion();
        ProcessInstance merged = (ProcessInstance)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId_(), id);
        Assert.assertTrue("Version for 'ProcessInstance' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProcessInstanceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to initialize correctly", dod.getRandomProcessInstance());
        ProcessInstance obj = dod.getNewTransientProcessInstance(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProcessInstance' identifier to be null", obj.getId_());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ProcessInstance' identifier to no longer be null", obj.getId_());
    }
    
    @Test
    public void ProcessInstanceIntegrationTest.testRemove() {
        ProcessInstance obj = dod.getRandomProcessInstance();
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'ProcessInstance' failed to provide an identifier", id);
        obj = ProcessInstance.findProcessInstance(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProcessInstance' with identifier '" + id + "'", ProcessInstance.findProcessInstance(id));
    }
    
}
