// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.activiti.engine.ProcessEngine;
import org.activiti.spring.rest.model.UserRecord;
import org.activiti.spring.rest.model.UserRecordDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect UserRecordDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserRecordDataOnDemand: @Component;
    
    private Random UserRecordDataOnDemand.rnd = new SecureRandom();
    
    private List<UserRecord> UserRecordDataOnDemand.data;
    
    public UserRecord UserRecordDataOnDemand.getNewTransientUserRecord(int index) {
        UserRecord obj = new UserRecord();
        setEmail(obj, index);
        setFirstName(obj, index);
        setId(obj, index);
        setLastName(obj, index);
        setProcessEngine(obj, index);
        return obj;
    }
    
    public void UserRecordDataOnDemand.setEmail(UserRecord obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void UserRecordDataOnDemand.setFirstName(UserRecord obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void UserRecordDataOnDemand.setId(UserRecord obj, int index) {
        String id = "id_" + index;
        obj.setId(id);
    }
    
    public void UserRecordDataOnDemand.setLastName(UserRecord obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void UserRecordDataOnDemand.setProcessEngine(UserRecord obj, int index) {
        ProcessEngine processEngine = null;
        obj.setProcessEngine(processEngine);
    }
    
    public UserRecord UserRecordDataOnDemand.getSpecificUserRecord(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserRecord obj = data.get(index);
        Long id = obj.getId_();
        return UserRecord.findUserRecord(id);
    }
    
    public UserRecord UserRecordDataOnDemand.getRandomUserRecord() {
        init();
        UserRecord obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId_();
        return UserRecord.findUserRecord(id);
    }
    
    public boolean UserRecordDataOnDemand.modifyUserRecord(UserRecord obj) {
        return false;
    }
    
    public void UserRecordDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserRecord.findUserRecordEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserRecord' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserRecord>();
        for (int i = 0; i < 10; i++) {
            UserRecord obj = getNewTransientUserRecord(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
