// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import java.io.Serializable;
import org.activiti.spring.rest.model.UserInfo;

privileged aspect UserInfo_Roo_Serializable {
    
    declare parents: UserInfo implements Serializable;
    
    private static final long UserInfo.serialVersionUID = 1L;
    
}
