// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import java.io.Serializable;
import org.activiti.spring.rest.model.UserGroup;

privileged aspect UserGroup_Roo_Serializable {
    
    declare parents: UserGroup implements Serializable;
    
    private static final long UserGroup.serialVersionUID = 1L;
    
}
