@startuml
!include /home/tstephen/git/crm/docs/src/main/plantuml/stylesheet.puml.txt

node "Omny Link" {
  HTTP -- [catalog] : REST
  HTTP -- [custmgmt] : REST

  [catalog] ..> [custmgmt] : use
  [catalog] ..> [support-services] : use

  [custmgmt] ..> [support-services] : use

  [catalog] ..> [OL_* tables] : use
  [custmgmt] ..> [OL_* tables] : use
}

[support-services]
note left of [support-services]
  Notes, Documents, Media
end note

database "MySql" {
  frame "OL_* tables" {
  }
}
@enduml