[[build-report]]
=== icon:check-circle-o[] Build report

Actor: Report Developer

==== User story

When a client-specific requirement crops up there is a choice of either 
enhancing the product features set or doing something solely for that client. 

<<build-simple-report>>, both tabular and 
charts, is a roadmap story but that will always favour simplicity over power. 
This story allows a fuller range of options but requires development skills of 
the user.

==== User outcome

A new toolbar entry that when clicked displays the report in the browser with 
the option of a PDF download of the same material.

==== Pre-requisites

The developer should be familiar with 
http://community.jaspersoft.com/project/jaspersoft-studio[Jasper Reports, role="external" window=="_blank"],
an open source tool including both design and runtime components.



This is fully custom development and as such can be a stand-alone piece of work.
There is no template for ordering such a custom report beyond liaising with your
report developer in conjunction with the Omny data model.