[[build-simple-report]]
=== icon:warning[] Build 'simple' report

Actor: Client staff

==== User story

The client may wish to create views of the data that are not provided as 
standard. This story allows the simpler of such requirements to be delivered
by providing a simple 'wizard' to define a report. More complex reports are 
supported by <<build-report,Build report>>.

The wizard will allow the user to define the following:

 - Choose 'primary' entity the report is based around (Contact, Account, Order 
 etc.)
 - Choose fields of that entity to display (including custom ones and, with 
 some limitations, related entity fields)
 - Choose aggregations (sum, average, count)
 - Choose group by
 - Choose type (table or bar chart initially)
 - Save / deploy for own use
 - Share / publish report to other users of the same client and / or to the 
 public

==== User outcome

A new toolbar entry that when clicked displays the report in the browser with 
the option of a PDF download of the same material. Implicit in this is the 
ability to https://en.wikipedia.org/wiki/Deep_linking[deep link, role="external", window="_blank"] 
to the report. 

==== Pre-requisites



==== Order Form

TBD