// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import java.io.Serializable;
import org.activiti.spring.rest.model.Deployment;

privileged aspect Deployment_Roo_Serializable {
    
    declare parents: Deployment implements Serializable;
    
    private static final long Deployment.serialVersionUID = 1L;
    
}
