// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import java.io.Serializable;
import org.activiti.spring.rest.model.Form;

privileged aspect Form_Roo_Serializable {
    
    declare parents: Form implements Serializable;
    
    private static final long Form.serialVersionUID = 1L;
    
}
