// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import javax.persistence.Entity;
import org.activiti.spring.rest.model.ProcessInstance;

privileged aspect ProcessInstance_Roo_Jpa_Entity {
    
    declare @type: ProcessInstance: @Entity;
    
}
