[[howto-add-custom-partials]]
=== HOWTO add custom user interface sections (partials)

==== Overview

'Partials' refers to partial pages of HTML that make up the user interface.
Typically, each partial renders one or more sections with its own heading.  
There are three kinds of partials making up each page:

- **Base partials** provide things like the toolbar, headings etc. and also the
basic entity list and editing presented by each page.
- **Standard extension partials** render the tenant-specific extension fields
as well as possible without any knowledge about what those fields are for. They
are aware of a range of standard controls (see <<howto-add-custom-fields>>) and
present them in the order they appear in the tenant configuration file in one
column on small screens or two on larger ones. 
- **Custom extension partials** allow a greater degree of control over the
layout of custom fields, for example to group several fields together or to
introduce custom logic.

Base and standard extension partials are provided within the application. The
following section runs through an example of creating and configuring a
custom extension partial.  

==== Details

. Find the `partials` section of the tenant configuration file. 

. Each partial entry consists of a name-url pair. The name must be one of a list
expected by the application. It is constructed from the tenant id, entity name
and 'Extension' as a suffix. The URL specifies the location of your custom html.
For example:
+
[source,json]
----
  { "name": "acmeAccountExtension", "url": "https://acme.com/omny/partials/account-extension.html" }
----

. Next, write your custom partial. Standard HTML is augmented in a couple of ways:

  - https://ractive.js.org/[Ractive] provides data binding
  - https://github.com/janl/mustache.js/ provides minimal templating with {{mustaches}} in JavaScript 
+
These examples should get you started, or examine the application source for the
page you're trying to extend for more ideas.
+
  - link:acctmgmt/partial-examples/contact-extension.1.html[**contact-extension.1.html**] the inevitable `hello world`  
  - link:acctmgmt/partial-examples/contact-extension.2.html[**contact-extension.2.html**] add a collapsible section without any fields
  - link:acctmgmt/partial-examples/contact-extension.3.html[**contact-extension.3.html**] add a single field with data binding
