[[howto-add-custom-fields]]
=== HOWTO add custom fields

==== Overview

Omny comes with a number of standard entities, each of which has its own
standard fields covering common usages. However, many tenants have requirements
to add additional fields. Any entity can be extended in this way simply by
adding them into the tenant configuration file, the following section shows how.

==== Details

. First identify which entity you wish to extend.

. Next, find the `entityFields` section in the tenant configuration file.
For example, to add a field to contact records, look for the 
`contactFields` section. If it's missing simply add an array like this:
+
[source,json]
----
"contactFields": [
],
----
. Adding custom fields minimally consists of a mandatory `name` attribute:
+
[source,json]
----
"contactFields": [
  { "name": "jobTitle" }
],
----
+
Note that keys follow the JavaScript 'camelCase' naming convention. If this is
all that is provided, the application will assume it is a text control and
derive a label (in this case resulting in 'Job Title').

. You may also specify some or all of the following attributes:
  - **hint** specifies user instructions that appear below the field, to use 
  this most effectively use the tenant's language and keep it to a dozen or so words ;
  - **label** allows you override the derived ones ;
  - **required** set to `true` if this field must be specified before the record can be saved, use sparingly ; 
  - **type** specifies one of the supported control types rather than just text
  (checkbox, date, email, list, select, multi-select, url, time, account and contact) ;
  - **validation** specifies a regular expression that will be used as the HTML
  pattern attribute. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-pattern[Read documentation]
+
Here is a full example:
+
[source,json]
----
"contactFields": [
  { "name": "dob", "label": "Date of Birth", "type": "date", "hint": "If specified, we'll send an e-card" }
],
----

. If type is specified as `list` remember to check suitable options are 
specified, see <<howto-edit-lists>>.
 
. View the https://api.omny.link/status.html[status page] to check the configuration is as you expect.
