[[howto-edit-lists]]
=== HOWTO edit lists

==== Overview

Lists exist in the system in a number of places and may be attached to both
standard and custom fields. They are maintained within the tenant configuration
file.

==== Details

. Find the `typeaheadControls` section and check if the expected list is present
or if not create it. Each list looks like this:
+
[source,json]
----
  { "name": "camelCaseListName", "selector": "#curFieldName", "values": [] }
----
+ 
By convention, if the list is, say, a list of account types we name the list 
`accountTypes` and the selector will be `#curAccountType` (singular).

. Values are objects containing the hidden identifier and the display name, for
example:
+
[source,json]
----
  {  "id": "Staff", "name": "Staff"  }
----
+
Identifiers should generally not contain spaces.

. Finally, in some cases, notably the `stage` list, there is also an idx. This is
used to order records with -1 meaning an inactive record. For example: 

[source,json]
----
  {  "idx": -1, "id": "Cold", "name": "Cold"  }
----