[[howto-edit-toolbar]]
=== HOWTO edit Omny toolbar

==== Overview

The toolbar is the sidebar that allows separate pages to the grouped together
as an application. 

==== Details

. Find the `toolbar` section of the tenant configuration file. Note that the 
order that the entries are displayed is the same as the order they appear in the. 
Generally we encourage clients to have the work management and 
contacts / accounts at the top and other more advanced items lower down but 
each can say what makes most sense to them.

. Each toolbar entry consists of: 
  
  - **url:** The page name, e.g. accounts.html
  - **classes:** Used to define an icon (and potentially other custom CSS classes
  - **description:** A slightly longer description of this page's purpose that is displayed on the index page
  - **role:** If specified, the user will only be presented this option if their account has the named link:index.html#role[role]
  - **title:** The short name for the toolbar icon, displayed as a tool tip

For example:
[source,json]
----
  { 
    "url": "accounts.html", 
    "classes": "glyphicon omny-icon-address-book", 
    "description": "Find and manage a particular school", 
    "title": "Account Management" 
  }
----

Icons can be selected from those available within http://getbootstrap.com/components/[Bootstrap 3]