[[howto-manage-tenant-config]]
=== HOWTO manage the tenant configuration file

==== Overview

The tenant configuration file is made up of a number of separate sections. 
We'll introduce each in turn then look at the details of how they work. The
file is essentially text based and designed to be hand edited though care must 
be taken to ensure it remains valid JSON.

Below you see the basic structure. 

[source,json]
--------------
  { 
    "id": "alife",
    "name": "A-Life",
    "theme": {
      ...
    },
    "show": {
      ...
    },
    "accountActions": [
      ...
    ],
    "accountFields": [
      ...
    ],
    "contactFields": [
       ...
    ],
    "contactActions": [
       ...
    ],
    "feedbackFields": [
       ...
    ],
    "toolbar": [
      ...
    ],
    "orderActions": [
      ...
    ],
    "orderFields": [
       ...
    ],
    "orderItemFields": [
      ...
    ],
    "partials": [
      ...
    ],
    "processes": [
      ...
    ],
    "serviceLevel": {
      ...
    },
    "stockCategoryFields": [
      ...
    ],
    "stockItemFields": [ 
      ...
    ],
    "stockItemActions": [
      ...
    ],
    "strings": {
      ...
    },
    "templates": [
      ...
    ],
    "typeaheadControls": [
      ...
    ],
    "workActions": [
      ...
    ]
  }
--------------

==== Sections

. id & name: These are simple attributes providing the machine and human 
readable names for the tenant.  

. theme: Branding settings to allow each tenant to put their own stamp on the 
application.

. show: This is the key section for determining which functionality a tenant 
has access to. For all the available settings see 
link:devops.html#howto-show-standard-sections[here].

. xxxActions and xxxFields: Each key entity of the system may be extended by 
having additional (custom) fields associated with it and actions, defined in 
workflows, that related to it. So contactActions are actions triggered in the 
context of a particular contact and contactFields are custom fields available 
to each contact.

. toolbar: Defines the links to show in the application sidebar and which 
provide the global navigation between different pages (or views). For details see 
link:devops.html#howto-edit-toolbar[here].

. partials: These are HTML fragments including data binding (moustaches) that 
allow per-tenant control over how custom fields are displayed and edited. These 
are optional and if not present custom fields are simply listed in the order 
they appear in the configuration file. In practice this is fine if only a couple
of fields exist but once the list grows it becomes necessary to define logical 
groupings.

. processes: Both standard (Omny Link namespace) and custom processes (client 
namespace) are listed here because each tenancy has a completely separate 
process repository.

. strings: Labels can be inferred from field names but tenants commonly refer
to similar concepts with a range of terminology, for example a tenant may refer 
to customer organisations as Accounts, Companies, Schools, Charities etc. The 
strings section allows Omny terms to be mapped to client terms. For details see 
link:devops.html#howto-edit-strings[here].

. templates: Templates, also known as Memo Templates encapsulate the notion 
of a pro-forma to be filled with data prior as an email, SMS, document etc. 
Short and long form variants are included to permit user preference of how to 
receive communication though currently this choice is made by the sender rather
than receiver.

. typeaheadControls: Lists that are used in various places especially for 
typeahead or autocomplete controls. For details see 
link:devops.html#howto-edit-lists[here].