[[register-user-for-tenant]]
=== icon:check-circle-o[] Register a user for a tenant

==== Actor

* Primary: Omny staff
* Secondary: New user of a particular tenant

==== User story

A tenant may wish to have users pre-registered as opposed to registering 
themselves, which is a service that we offer under certain circumstances.

This fulfills all aspects of the account creation, including entering the user 
in the CRM assigning access rights and sending a welcome mail.

==== User outcome

The user will receive an email containing a password to login with.

==== Pre-requisites

* <<create-tenancy>>
* Template with the name `WelcomeNewUser`, see <<maintain-template>>

==== Order Form

This feature needs no special enablement but is only available to Omny staff.

[Note]
=======
Before starting, ensure that the necessary template (`WelcomeNewUser`) 
exists *in the tenancy*, not omny.
=======

1. First ensure you are logged into the `omny` tenancy 
2. Navigate to the work management page where within the task 
menu there is an option to `Register user`, _provided you have the rights 
to see it_. Click it 
3. Provide the required details in the form, taking special care to enter the
tenant id correctly. Otherwise the user will be assigned the wrong access 
rights.