[[reset-others-password]]
=== Reset password for someone else

==== Actor

* Primary: System administrator or SDU analyst
* Secondary: End user of the system

Requires <<roles,`admin` role>>.

==== User story

In normal use any user can reset his or her own password using 
<<reset-password,Reset own password>>. However there may be circumstances
in which it is simply more convenient for an administrator to reset the password
on the user's behalf. 

The administrator accesses a full list of all users and from there initiates
an email to send the user a new password. Note that the administrator cannot 
see the old or the new passwords. 

==== Exclusions ====
 
This story does not cater for the situation that the user 
has lost access to the registered email account as well as the password. That 
would pose a risk of the administrator being tricked into re-assigning an 
account to someone entirely different.

==== User outcome

The user is able to login using the new password received in email and 
optionally to <<reset-own-password,reset that password>>.
