[[roles]]
=== Roles

Roles are what grant users permission to access the system and add, change or 
delete data. Roles are cumulative so it is usual for most users to have several
unlike job titles where each member of staff has just one.

A summary of the roles that exist and the permissions they confer is shown 
below:

* `User` - The initial state of a user after link:register-user.adoc[registration].
No specific capabilities beyond viewing own profile page ;
* `Sales` - Individual sales person functionality such as managing leads 
(contacts view) ;
* `Sales_Manager` - Provides escalation to the Sales people such as overriding 
discounts. _Not used by every tenant_ ;
* `Power_User` - Confers less common features like importing or exporting data ; 
* `Admin` - Change more sensitive parts of how the system behaves, particularly 
to register or change users and roles ;
* `Super_Admin` - A special role to allow access to more than one tenant.
* `Developer` - Provides code level configuration, manages Gitlab etc.

Whilst the general principles apply to all tenants specific user interface 
elements (such as tool bar) can be tailored to each tenant.  
  
INFO: _Names_ of roles look like `Power_User` but internally the ids are 
`power_user`.