// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.web;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.activiti.spring.rest.model.UserGroup;
import org.activiti.spring.rest.model.UserGroupDataOnDemand;
import org.activiti.spring.rest.web.UserGroupIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserGroupIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserGroupIntegrationTest: @Transactional;
    
    @Autowired
    UserGroupDataOnDemand UserGroupIntegrationTest.dod;
    
    @Test
    public void UserGroupIntegrationTest.testCountUserGroups() {
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to initialize correctly", dod.getRandomUserGroup());
        long count = UserGroup.countUserGroups();
        Assert.assertTrue("Counter for 'UserGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserGroupIntegrationTest.testFindUserGroup() {
        UserGroup obj = dod.getRandomUserGroup();
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to provide an identifier", id);
        obj = UserGroup.findUserGroup(id);
        Assert.assertNotNull("Find method for 'UserGroup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserGroup' returned the incorrect identifier", id, obj.getId_());
    }
    
    @Test
    public void UserGroupIntegrationTest.testFindAllUserGroups() {
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to initialize correctly", dod.getRandomUserGroup());
        long count = UserGroup.countUserGroups();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserGroup> result = UserGroup.findAllUserGroups();
        Assert.assertNotNull("Find all method for 'UserGroup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserGroupIntegrationTest.testFindUserGroupEntries() {
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to initialize correctly", dod.getRandomUserGroup());
        long count = UserGroup.countUserGroups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserGroup> result = UserGroup.findUserGroupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserGroup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserGroupIntegrationTest.testFlush() {
        UserGroup obj = dod.getRandomUserGroup();
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to provide an identifier", id);
        obj = UserGroup.findUserGroup(id);
        Assert.assertNotNull("Find method for 'UserGroup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserGroup(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserGroup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserGroupIntegrationTest.testMergeUpdate() {
        UserGroup obj = dod.getRandomUserGroup();
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to provide an identifier", id);
        obj = UserGroup.findUserGroup(id);
        boolean modified =  dod.modifyUserGroup(obj);
        Integer currentVersion = obj.getVersion();
        UserGroup merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId_(), id);
        Assert.assertTrue("Version for 'UserGroup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserGroupIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to initialize correctly", dod.getRandomUserGroup());
        UserGroup obj = dod.getNewTransientUserGroup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserGroup' identifier to be null", obj.getId_());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UserGroup' identifier to no longer be null", obj.getId_());
    }
    
    @Test
    public void UserGroupIntegrationTest.testRemove() {
        UserGroup obj = dod.getRandomUserGroup();
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'UserGroup' failed to provide an identifier", id);
        obj = UserGroup.findUserGroup(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserGroup' with identifier '" + id + "'", UserGroup.findUserGroup(id));
    }
    
}
