// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.activiti.spring.rest.model;

import org.activiti.spring.rest.model.FormDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FormDataOnDemand_Roo_Configurable {
    
    declare @type: FormDataOnDemand: @Configurable;
    
}
