spring.jpa.open-in-view = false
spring.jackson.mapper.default-view-inclusion=true

spring.threads.virtual.enabled=true

spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:liquibase-changelog.xml
