#-------------------------------------------------------------------------------
# Copyright 2015-2018 Tim Stephenson and contributors
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License.  You may obtain a copy
#  of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.
#-------------------------------------------------------------------------------
server.port = 8082

spring.application.name=Omny Link

#spring.datasource.url=jdbc:postgresql://localhost/crm
#spring.datasource.username=crm
#spring.datasource.password=secret
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.connection-test-query=SELECT 1;

# Take care that all JSON contains a time component or this will cause a failure
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
#spring.jackson.joda-date-time-format=yyyy-MM-dd HH:mm
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=always

#Hibernate property values are none, validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.generate-ddl=false
spring.jpa.show-sql=false

spring.freemarker.cache=false

#
# LOGGING PROPERTIES
#

logging.level.com.zaxxer.hikari=WARN
logging.level.com.knowprocess=WARN
logging.level.HikariPool=WARN
logging.level.link.omny=WARN
logging.level.org.apache=WARN
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.openid4java=WARN
logging.level.org.springframework=WARN
logging.level.org.springframework.boot=WARN
logging.level.org.subethamail.smtp=WARN
logging.level.springfox.documentation=WARN
