[[create-ad-hoc-task]]
=== icon:check-circle-o[] Create Ad-hoc task

Actor: Client Staff 

==== User story

From time to time a user may wish to create a reminder to do 
something, probably at some time in the future.

The 'Add task' action is available in several views and in each case asks for: 

 * What needs to be done: a short description of the task
 * When is it expected: This becomes the due date for the task
 * Who should do it: Choose from the users in your tenancy to decide who will 
   do this task. Or type one of the <<roles>> to offer to several people at once.  
 * Anyone who ought to be kept informed of task's progress
 * Where's the best place for the task: This is currently just an FYI

TIP: _Offer_ and _allocate_ are key terms in workflow. Currently in Omny all 
tasks are _offered_ meaning that they are not locked or committed to and may 
therefore be reassigned by anyone entitled to see them. Clearly _offering_ to 
just one person is more or less the same as allocating to that individual since
no one else can see the task. 

==== User outcome

A new task is created and immediately visible for the addressee(s). 

==== Pre-requisites

 * <<create-tenant>>

==== Order Form
To enable this story please use: http://omny.link/provision-work-mgmt/[Provision Work Management]

Implementation guide is link:devops.html#howto-enable-work-mgmt[here].