[[view-tasks]]
=== icon:check-circle-o[] View tasks

Actor: Client Staff

==== User story
At any given time there are many things happening across different aspects of a 
small business. To keep on top of all these things the user wants a single place
to go to see the work to be done.

WARNING: How people manage such work is quite a personal choice as everyone has their 
own habits and preferences, which is why there are so many tools on the market.
Omny's take is that we should be able to deliver the tasks to the tool of your 
choice so that the user and for you to use that familiar interface. With that 
said, currently tasks are only available in the embedded view.

Tasks include those raised by the system; ad-hoc tasks created by other users 
and tasks due to custom workflows.

==== User outcome

The user is able to view and process a list of tasks currently pending. Colours
indicate what is overdue (red); imminently due (amber) and further off (grey).
Various filtering and sorting is also available.

Together with <<create-ad-hoc-task>> this provides the basic work management 
functionality. 

==== Pre-requisites

 * <<create-tenancy>>
 * <<create-ad-hoc-task>>

==== Order Form

To enable this story please use: http://omny.link/provision-work-mgmt/[Provision Work Management]

Implementation guide is link:devops.html#howto-enable-work-mgmt[here].