[[howto-catalog-actions]]
=== HOWTO enable catalogue actions

==== Overview

Although actions are often defined specifically for each client there are
some that many clients find useful listed here. Enabling an action consists of
three parts:

. Add the action that will appear in the 'play' button drop down
. (optionally) Specify a partial that will be displayed in the dialogue
. Specify the workflow process that will handle the desired behaviour when the
action dialogue is submitted.

==== Details

===== Add order to account or contact

This action is applicable to either the account or contact page, allowing them
to create a new order for that prospect. To implement it use these snippets:

. Add to orderActions
+
[source,json]
----
  { "name": "Add ...", "ref": "AddOrderItems", "url": true  }
----
. Add to partials
+
[source,json]
----
  { "name": "xxxAddOrderItems", "url": "/partials/add-order.html"}
----
NOTE: xxx should be replaced with the tenant id.
+
. Add to processes
+
[source,json]
----
  { "name": "Add order items", "ref": "AddOrderItems", "url": "processes/link/omny/catalog/AddOrderItems.bpmn" }
----

==== Add order item to order

Sometimes an order is made up of separate order items (like items in a shopping
basket). In this we need an action to add new items to an order.

To implement, use these snippets:

. Add to accountActions or contactActions
+
[source,json]
----
  { "name": "Add ...", "ref": "AddOrderItem", "url": true  }
----
+
. Add to partials
+
[source,json]
----
  { "name": "xxxAddOrderItem", "url": "/partials/add-order-item.html"}
----
NOTE: xxx should be replaced with the tenant id.
+
. Add to processes
+
[source,json]
----
  { "name": "Add order item", "ref": "AddOrderItem", "url": "processes/link/omny/catalog/AddOrderItem.bpmn" }
----
