== Introduction

Omny Link is an open source CRM. Unlike many such tools it is built specifically 
with flexibility in mind because every customer needs to analyse their 
customer data and react to events as the occur (or even try to anticipate them).

This flexibility is delivered because:

* It is built _API-first_: First and foremost every service of the CRM is defined 
as a set of micro-services that can be invoked directly by their REST API. Our 
user interface is just one example of doing this.
* It embeds a full BPMN 2 process engine: Pair this industry standard for 
defining workflow with Omny REST services for highly agile and yet still 
uniquely tailored solutions.
* It also embeds a DMN decision engine: The decision engine allows formal
description of how your business makes decisions and the ability to re-configure
them as circumstances change.

This documentation is structured around a set of user stories so you can quickly
find the way that Omny is able to satisfy problems you already recognise.   

=== Conventions in this guide

 * *Status:* The software is under active development so current status is 
 shown as follows: 
   ** icon:check-circle-o[] Available now.
   ** icon:unlock[] Scheduled: We operate a continuous deployment strategy 
   so features are released frequently but this could be up to 3 months away.
   ** icon:warning[] Roadmap: A feature currently planned at some future stage  
   but subject to change without warning.