== Introduction

Omny Link is an open source CRM. Unlike many such tools it is built 
specifically with flexibility in mind because every customer needs to analyse their customer data and react to events as they occur.

This flexibility is delivered because:

* Built _API-first_: First and foremost every service of the CRM is defined 
as a set of micro-services that can be invoked directly by their REST API. A sample user interface is provided but is just one example of interacting with the API.
* Standard fields: Experience shows these are the things required by all clients so they are 'built-in'.
* Custom fields: Every business needs to store additional data specific to its sector, products and procedures. These are easily added to an installation through no-code configuration. 

This documentation is structured around a set of user stories so you can quickly
find the way that Omny is able to satisfy problems you already recognise.   

=== Conventions in this guide

 * *Status:* The software is under active development so current status is 
 shown as follows: 
   ** icon:check-circle-o[] Available now.
   ** icon:unlock[] Scheduled: We operate a continuous deployment strategy 
   so features are released frequently but this could be up to 3 months away.
   ** icon:warning[] Roadmap: A feature currently planned at some future stage  
   but subject to change without warning.