name: Build, test, integration-test with Maven

on:
  push:
  pull_request:
    types: [synchronize, reopened] # omit 'opened' as already run on push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4.2.2

    - name: Set up JDK
      uses: actions/setup-java@v4.7.1
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # Step that does that actual cache save and restore
    - uses: actions/cache@v4.2.3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B integration-test --file pom.xml
